"use client";

import { useEffect, useRef, useState } from "react";
import { ArrowRight } from "lucide-react";
import { useStepStore } from "@/store/step-store";
import { useStepNavigationStore } from "@/store/step-navigation-store";
import { getNextStep } from "@/_config/pipeline-flow";
import MarkdownRenderer from "@/components/MarkdownRenderer";
import StageInputBar from "@/components/StageInputBar";
import type { StepUIProps } from "../../../_shared/types";

// ─── Icons ─────────────────────────────────────────────────────────────────
function SpinnerIcon() {
  return (
    <svg
      className="animate-spin"
      width="14"
      height="14"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2.5"
      strokeLinecap="round"
    >
      <path d="M12 2v4M12 18v4M4.93 4.93l2.83 2.83M16.24 16.24l2.83 2.83M2 12h4M18 12h4M4.93 19.07l2.83-2.83M16.24 7.76l2.83-2.83" />
    </svg>
  );
}

// ─── Main Component ────────────────────────────────────────────────────────
export function QaUI(props: StepUIProps) {
  const step = useStepStore((s) => s.steps.qa);
  const streamingContent = useStepStore((s) => s.streamingContent);
  const currentStep = useStepStore((s) => s.currentStep);
  const isRunning = useStepStore((s) => s.isRunning);
  const featureBrief = useStepStore((s) => s.featureBrief);
  const steps = useStepStore((s) => s.steps);
  const isHydrated = useStepStore((s) => s.isHydrated);
  const executeStep = useStepStore((s) => s.executeStep);

  const tier = useStepNavigationStore((s) => s.tier);
  const nextStep = getNextStep("qa", tier);

  const [editInput, setEditInput] = useState("");
  const autoStartedRef = useRef(false);
  const bottomRef = useRef<HTMLDivElement>(null);

  // Auto-start: when PRD is available and QA hasn't been generated yet
  useEffect(() => {
    if (!isHydrated) return;
    if (autoStartedRef.current) return;
    if (isRunning) return;
    if (step?.content) return;
    const prdContent = steps.prd?.content ?? featureBrief;
    if (!prdContent.trim()) return;
    autoStartedRef.current = true;
    void executeStep("qa");
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isHydrated, steps.prd?.content, step?.content, featureBrief]);

  const isThisRunning = isRunning && currentStep === "qa";
  const content = isThisRunning ? streamingContent : (step?.content ?? "");
  const isDone = step?.status === "completed";

  // Auto-scroll to bottom during SSE streaming
  useEffect(() => {
    if (isThisRunning && content) {
      bottomRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
    }
  }, [content, isThisRunning]);

  return (
    <div className="flex flex-1 flex-col h-full overflow-hidden">
      <div className="flex-1 overflow-auto px-8 py-8">
        <div className="w-full h-full">
          <div className="bg-white border border-[#e2e8f0] rounded-[4px] shadow-[0px_1px_2px_0px_rgba(0,0,0,0.05)] overflow-hidden">
            <div className="bg-[rgba(248,250,252,0.5)] border-b border-[#f1f5f9] px-8 pt-8 pb-[33px] flex items-start justify-between">
              <div className="flex flex-col gap-1">
                <div className="flex items-center gap-2 mb-1">
                  <span className="bg-[rgba(113,42,226,0.1)] text-[#712ae2] text-[12px] font-normal px-2 py-[2px] rounded-[2px] font-['Space_Grotesk',sans-serif]">
                    {isThisRunning ? "GENERATING…" : isDone ? "DRAFT V1.0" : "PENDING"}
                  </span>
                  {isDone && (
                    <span className="text-[#94a3b8] text-[12px]">
                      {step?.durationMs != null
                        ? `Generated in ${(step.durationMs / 1000).toFixed(1)}s`
                        : "Just now"}
                    </span>
                  )}
                </div>
                <h2 className="text-[30px] font-semibold text-[#0f172a] tracking-[-0.3px] leading-[36px]">
                  QA Plan
                </h2>
                <p className="text-[14px] text-[#64748b] leading-[21px]">
                  {step?.model ? (
                    <>
                      Generated by{" "}
                      <span className="font-medium">{step.model}</span>
                    </>
                  ) : (
                    "Quality assurance checklist verifying all requirements are covered before kick-off"
                  )}
                </p>
                {isDone && step?.costUsd != null && (
                  <div className="flex items-center gap-4 mt-1">
                    <span className="text-[11px] text-[#94a3b8]">
                      Cost:{" "}
                      <span className="font-medium text-[#64748b]">
                        ${step.costUsd.toFixed(4)}
                      </span>
                    </span>
                  </div>
                )}
              </div>
            </div>
            <div className="p-8">
              {!content && !isThisRunning ? (
                <div className="flex flex-col items-center justify-center py-20 gap-3 text-[#94a3b8]">
                  <span className="text-[13px]">Waiting for pipeline to start…</span>
                </div>
              ) : isThisRunning && !content ? (
                <div className="flex items-center gap-2 text-[#712ae2] text-[13px]">
                  <SpinnerIcon /> Generating QA Plan…
                </div>
              ) : (
                <MarkdownRenderer content={content} variant="default" />
              )}
              <div ref={bottomRef} />
            </div>
          </div>
        </div>
      </div>

      <StageInputBar
        value={editInput}
        onChange={setEditInput}
        onSubmit={() => {
          const instruction = editInput.trim();
          if (!instruction || isThisRunning) return;
          setEditInput("");
          void executeStep("qa", instruction);
        }}
        placeholder="Ask AgenticBuilder to refine this QA plan…"
        disabled={isThisRunning}
        actions={
          <div className="flex items-center gap-3 shrink-0">
            <button
              onClick={() => { if (nextStep) props.onNavigate(nextStep); }}
              disabled={!isDone}
              className="flex items-center gap-2 text-white bg-indigo-600 hover:bg-indigo-500 rounded-lg h-10 px-4 shrink-0 text-sm font-semibold shadow-md hover:shadow-indigo-200 hover:shadow-lg transition-all hover:scale-105 active:scale-95 disabled:opacity-40 disabled:cursor-not-allowed disabled:hover:scale-100 disabled:hover:shadow-none"
            >
              Next Step
              <ArrowRight size={16} color="white" />
            </button>
          </div>
        }
      />
    </div>
  );
}
