"use client";

/**
 * Shared layout for all "document viewer" pipeline steps
 * (prd, trd, sysdesign, implguide, design, pencil, mockup, qa, verify).
 *
 * Ported from _DocViewerSubStage.tsx — uses new step-navigation store.
 */

import { useState } from "react";
import {
  Share2, MoreVertical, Download, ArrowRight, Sparkles,
  Loader2, Send, CheckCircle2,
} from "lucide-react";
import MarkdownRenderer from "@/components/MarkdownRenderer";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Separator } from "@/components/ui/separator";
import { ScrollArea } from "@/components/ui/scroll-area";
import { useStepNavigationStore } from "@/store/step-navigation-store";
import type { StepId } from "@/_config/pipeline-flow";

type DocTab = "prd" | "design" | "trd" | "qa";

const DOC_TABS: { id: DocTab; label: string; stepTarget: StepId }[] = [
  { id: "prd",    label: "PRD",              stepTarget: "prd" },
  { id: "design", label: "Design Document",  stepTarget: "design" },
  { id: "trd",    label: "Technical Specs",  stepTarget: "trd" },
  { id: "qa",     label: "QA Plan",          stepTarget: "qa" },
];

export interface DocViewerUiProps {
  activeTabId?: DocTab;
  title: string;
  subtitle: string;
  generatingLabel?: string;
  editPlaceholder: string;
  isRunning: boolean;
  isDone: boolean;
  onNavigate?: (stepId: StepId) => void;
  step?: {
    model?: string;
    costUsd?: number | null;
    durationMs?: number | null;
  } | null;
  content: string;
  extraContent?: React.ReactNode;
  confirmLabel: string;
  onConfirm: () => void;
  showDownload?: boolean;
  onDownload?: () => void;
  downloadLoading?: boolean;
  markdownVariant?: "prd" | "default";
}

export function DocViewerUi({
  activeTabId,
  title,
  subtitle,
  generatingLabel = "GENERATING…",
  editPlaceholder,
  isRunning,
  isDone,
  step,
  content,
  extraContent,
  confirmLabel,
  onConfirm,
  showDownload,
  onDownload,
  downloadLoading,
  markdownVariant = "default",
  onNavigate,
}: DocViewerUiProps) {
  const [editInput, setEditInput] = useState("");
  const goToStep = onNavigate ?? useStepNavigationStore((s) => s.goToStep);

  const statusLabel = isRunning ? generatingLabel : isDone ? "DRAFT V1.0" : "PENDING";

  return (
    <div className="flex flex-1 flex-col h-full overflow-hidden">

      {/* ── Doc Tab Bar ── */}
      <div className="shrink-0 bg-white border-b border-[#e2e8f0] flex items-center justify-between px-8">
        <div className="flex gap-6">
          {DOC_TABS.map((tab) => {
            const isActive = tab.id === activeTabId;
            return (
              <button
                key={tab.id}
                onClick={() => goToStep(tab.stepTarget)}
                className={[
                  "relative flex items-center gap-1.5 py-4 text-sm font-semibold transition-colors",
                  isActive
                    ? "text-[#712ae2] border-b-2 border-[#712ae2]"
                    : "text-[#94a3b8] hover:text-[#64748b]",
                ].join(" ")}
              >
                {tab.label}
                {isActive && isDone && <CheckCircle2 className="size-3.5" />}
              </button>
            );
          })}
        </div>
        <Button
          variant="outline"
          size="sm"
          onClick={() => goToStep("env-setup")}
          className="text-[#712ae2] border-[rgba(113,42,226,0.2)] hover:bg-[rgba(113,42,226,0.05)] hover:text-[#712ae2] text-xs font-bold"
        >
          Proceed to Kick-off
          <ArrowRight className="size-3" />
        </Button>
      </div>

      {/* ── Content Canvas ── */}
      <ScrollArea className="flex-1">
        <div className="px-8 py-8">
          <div className="w-full">
            <div className="bg-white border border-[#e2e8f0] rounded-lg shadow-sm overflow-hidden">

              {/* Document Header */}
              <div className="bg-[#fafbfc] border-b border-[#f1f5f9] px-8 pt-7 pb-7 flex items-start justify-between gap-4">
                <div className="flex flex-col gap-1.5">
                  {/* Status badge row */}
                  <div className="flex items-center gap-2">
                    <Badge variant={isRunning ? "warning" : isDone ? "default" : "muted"} className="rounded text-[11px] font-bold tracking-wide uppercase">
                      {isRunning && <Loader2 className="size-3 animate-spin" />}
                      {statusLabel}
                    </Badge>
                    {isDone && step?.durationMs != null && (
                      <span className="text-xs text-[#94a3b8]">
                        Generated in {(step.durationMs / 1000).toFixed(1)}s
                      </span>
                    )}
                  </div>
                  <h2 className="text-2xl font-semibold text-[#0f172a] tracking-tight">{title}</h2>
                  <p className="text-sm text-[#64748b]">
                    {step?.model
                      ? <>Generated by <span className="font-medium">{step.model}</span></>
                      : subtitle}
                  </p>
                  {isDone && step?.costUsd != null && (
                    <span className="text-xs text-[#94a3b8]">
                      Cost: <span className="font-medium text-[#64748b]">${step.costUsd.toFixed(4)}</span>
                    </span>
                  )}
                </div>
                <div className="flex items-center gap-0.5 shrink-0">
                  <Button variant="ghost" size="icon" className="h-8 w-8 text-[#94a3b8]">
                    <Share2 className="size-4" />
                  </Button>
                  <Button variant="ghost" size="icon" className="h-8 w-8 text-[#94a3b8]">
                    <MoreVertical className="size-4" />
                  </Button>
                </div>
              </div>

              {/* Document Body */}
              <div className="p-8">
                {!content && !isRunning ? (
                  <div className="flex flex-col items-center justify-center py-20 gap-3 text-[#94a3b8]">
                    <span className="text-sm">Waiting for pipeline to start…</span>
                  </div>
                ) : isRunning && !content ? (
                  <div className="flex items-center gap-2 text-[#712ae2] text-sm">
                    <Loader2 className="size-4 animate-spin" /> Generating…
                  </div>
                ) : (
                  <div className="flex flex-col gap-6">
                    {extraContent}
                    {content && <MarkdownRenderer content={content} variant={markdownVariant} />}
                  </div>
                )}
              </div>

            </div>
          </div>
        </div>
      </ScrollArea>

      {/* ── Footer ── */}
      <Separator />
      <div className="shrink-0 bg-white/90 backdrop-blur-sm flex items-center justify-between px-8 py-3 gap-6">
        {/* AI Edit Input */}
        <div className="flex-1 min-w-0 relative">
          <Sparkles className="absolute left-3 top-1/2 -translate-y-1/2 size-3.5 text-[#94a3b8] pointer-events-none" />
          <input
            value={editInput}
            onChange={(e) => setEditInput(e.target.value)}
            placeholder={editPlaceholder}
            className="w-full bg-[#f8fafc] border border-[#e2e8f0] rounded-md pl-9 pr-10 py-2.5 text-sm text-[#0f172a] placeholder:text-[#6b7280] focus:outline-none focus:ring-1 focus:ring-[#712ae2] focus:border-[#712ae2] transition-colors"
          />
          {editInput && (
            <button
              className="absolute right-2.5 top-1/2 -translate-y-1/2 text-[#712ae2] hover:opacity-70 transition-opacity"
              title="Send"
            >
              <Send className="size-3.5" />
            </button>
          )}
        </div>

        {/* Action Buttons */}
        <div className="flex items-center gap-2.5 shrink-0">
          {showDownload && (
            <Button
              variant="outline"
              size="sm"
              onClick={onDownload}
              disabled={!isDone || downloadLoading}
              className="font-semibold"
            >
              {downloadLoading ? <Loader2 className="size-3.5 animate-spin" /> : <Download className="size-3.5" />}
              {downloadLoading ? "Preparing…" : "Download PDF"}
            </Button>
          )}
          <Button
            size="sm"
            onClick={onConfirm}
            className="bg-[#712ae2] hover:bg-[#5b22b8] font-bold"
          >
            {confirmLabel}
            <ArrowRight className="size-3.5" />
          </Button>
        </div>
      </div>
    </div>
  );
}
