/**
 * Env file helpers for the generated-code workspace (kick-off / coding scaffold).
 */

import { randomBytes } from "crypto";

/** Prefer request body, then Agentic Builder server env (e.g. .env.local). */
export function resolveBlueprintGeneratedDatabaseUrl(
  requestOverride?: string | null,
): string | null {
  const v = (
    requestOverride ??
    process.env.BLUEPRINT_GENERATED_DATABASE_URL ??
    ""
  ).trim();
  return v.length > 0 ? v : null;
}

/** Generate a random hex string suitable for JWT_SECRET in dev/staging. */
function generateJwtSecret(): string {
  return randomBytes(32).toString("hex");
}

/** Minimal .env for generated-code; DATABASE_URL is JSON-quoted for special characters. */
export function formatGeneratedCodeDotEnv(databaseUrl: string): string {
  return [
    "# Generated by Agentic Builder at scaffold time.",
    "# Set BLUEPRINT_GENERATED_DATABASE_URL in Agentic Builder .env.local to override for new runs.",
    `DATABASE_URL=${JSON.stringify(databaseUrl)}`,
    `JWT_SECRET=${JSON.stringify(generateJwtSecret())}`,
    `JWT_EXPIRES_IN="7d"`,
    "",
  ].join("\n");
}

/** Upsert DATABASE_URL into an existing .env payload while preserving other keys. */
export function upsertDatabaseUrlEnv(
  envContent: string,
  databaseUrl: string,
): string {
  const serialized = `DATABASE_URL=${JSON.stringify(databaseUrl)}`;
  if (!envContent.trim()) return `${serialized}\n`;
  if (/^\s*DATABASE_URL\s*=.*$/m.test(envContent)) {
    return envContent.replace(/^\s*DATABASE_URL\s*=.*$/m, serialized);
  }
  const normalized = envContent.endsWith("\n") ? envContent : `${envContent}\n`;
  return `${normalized}${serialized}\n`;
}

/**
 * Upsert JWT_SECRET and JWT_EXPIRES_IN into an existing .env payload.
 * Only adds them if they are not already present, so user-set values are preserved.
 */
export function upsertJwtEnvVars(envContent: string): string {
  let result = envContent.endsWith("\n") ? envContent : `${envContent}\n`;

  if (!/^\s*JWT_SECRET\s*=/m.test(result)) {
    result += `JWT_SECRET=${JSON.stringify(generateJwtSecret())}\n`;
  }
  if (!/^\s*JWT_EXPIRES_IN\s*=/m.test(result)) {
    result += `JWT_EXPIRES_IN="7d"\n`;
  }
  return result;
}
