/**
 * Env file helpers for the generated-code workspace (kick-off / coding scaffold).
 */

/** Prefer request body, then Agentic Builder server env (e.g. .env.local). */
export function resolveBlueprintGeneratedDatabaseUrl(
  requestOverride?: string | null,
): string | null {
  const v = (
    requestOverride ??
    process.env.BLUEPRINT_GENERATED_DATABASE_URL ??
    ""
  ).trim();
  return v.length > 0 ? v : null;
}

/** Minimal .env for generated-code; DATABASE_URL is JSON-quoted for special characters. */
export function formatGeneratedCodeDotEnv(databaseUrl: string): string {
  return [
    "# Generated by Agentic Builder at scaffold time.",
    "# Set BLUEPRINT_GENERATED_DATABASE_URL in Agentic Builder .env.local to override for new runs.",
    `DATABASE_URL=${JSON.stringify(databaseUrl)}`,
    "",
  ].join("\n");
}

/**
 * Ensure PostgreSQL/Cockroach datasource includes `url = env("DATABASE_URL")` (Prisma 5/6).
 * No-op if a url line is already present.
 */
export function ensurePrismaDatasourceDatabaseUrl(schemaContent: string): string {
  if (/^\s*url\s*=\s*env\s*\(\s*["']DATABASE_URL["']\s*\)/m.test(schemaContent)) {
    return schemaContent;
  }
  return schemaContent.replace(
    /^(\s*provider\s*=\s*"(postgresql|cockroachdb)"\s*)\r?\n(\s*)\}/m,
    (_, provLine: string, indentBeforeClose: string) =>
      `${provLine}\n  url = env("DATABASE_URL")\n${indentBeforeClose}}`,
  );
}
