/**
 * Env file helpers for the generated-code workspace (kick-off / coding scaffold).
 *
 * Single source of truth for backend ↔ frontend port pairing. The shape of
 * the generated `.env` files is fixed here so that:
 *   • `backend/.env` always declares `PORT=<port>`
 *   • `frontend/.env` always declares `VITE_API_BASE_URL=http://localhost:<port>/api`
 * No worker should hard-code a different port in either file.
 */

import { randomBytes } from "crypto";

/**
 * Default backend port. Overridable per-run via the `BLUEPRINT_BACKEND_PORT`
 * env var on the Agentic Builder server (e.g. when port 4000 is taken).
 *
 * IMPORTANT: this MUST match the value of `PORT` in `backend/.env` and the
 * `localhost:<port>` segment in `frontend/.env`'s `VITE_API_BASE_URL`. The
 * helpers below preserve that invariant.
 */
export function resolveBackendPort(): number {
  const v = Number(process.env.BLUEPRINT_BACKEND_PORT ?? "");
  return Number.isFinite(v) && v > 0 && v < 65536 ? v : 4000;
}

/** Canonical `VITE_API_BASE_URL` for a given backend port. */
export function buildFrontendApiBaseUrl(backendPort: number): string {
  return `http://localhost:${backendPort}/api`;
}

/** Prefer request body, then Agentic Builder server env (e.g. .env.local). */
export function resolveBlueprintGeneratedDatabaseUrl(
  requestOverride?: string | null,
): string | null {
  const v = (
    requestOverride ??
    process.env.BLUEPRINT_GENERATED_DATABASE_URL ??
    ""
  ).trim();
  return v.length > 0 ? v : null;
}

/** Generate a random hex string suitable for JWT_SECRET in dev/staging. */
function generateJwtSecret(): string {
  return randomBytes(32).toString("hex");
}

/** Minimal .env for generated-code; DATABASE_URL is JSON-quoted for special characters. */
export function formatGeneratedCodeDotEnv(databaseUrl: string): string {
  const port = resolveBackendPort();
  return [
    "# Generated by Agentic Builder at scaffold time.",
    "# Set BLUEPRINT_GENERATED_DATABASE_URL in Agentic Builder .env.local to override for new runs.",
    "# Set BLUEPRINT_BACKEND_PORT to change the backend port (frontend .env will track automatically).",
    `PORT=${port}`,
    `DATABASE_URL=${JSON.stringify(databaseUrl)}`,
    `JWT_SECRET=${JSON.stringify(generateJwtSecret())}`,
    `JWT_EXPIRES_IN="7d"`,
    "",
  ].join("\n");
}

/**
 * Build the canonical `frontend/.env` for the generated workspace. Always
 * uses the same port that `formatGeneratedCodeDotEnv` writes into
 * `backend/.env`, so the two files can never drift.
 */
export function formatGeneratedFrontendDotEnv(): string {
  const port = resolveBackendPort();
  return [
    "# Generated by Agentic Builder at scaffold time.",
    "# Mirrors backend/.env's PORT (single source of truth: BLUEPRINT_BACKEND_PORT).",
    `VITE_API_BASE_URL=${buildFrontendApiBaseUrl(port)}`,
    "",
  ].join("\n");
}

/** Upsert DATABASE_URL into an existing .env payload while preserving other keys. */
export function upsertDatabaseUrlEnv(
  envContent: string,
  databaseUrl: string,
): string {
  const serialized = `DATABASE_URL=${JSON.stringify(databaseUrl)}`;
  if (!envContent.trim()) return `${serialized}\n`;
  if (/^\s*DATABASE_URL\s*=.*$/m.test(envContent)) {
    return envContent.replace(/^\s*DATABASE_URL\s*=.*$/m, serialized);
  }
  const normalized = envContent.endsWith("\n") ? envContent : `${envContent}\n`;
  return `${normalized}${serialized}\n`;
}

/** Upsert PORT (and align frontend VITE_API_BASE_URL) into an existing .env. */
export function upsertBackendPortEnv(
  envContent: string,
  port: number = resolveBackendPort(),
): string {
  const line = `PORT=${port}`;
  if (!envContent.trim()) return `${line}\n`;
  if (/^\s*PORT\s*=.*$/m.test(envContent)) {
    return envContent.replace(/^\s*PORT\s*=.*$/m, line);
  }
  const normalized = envContent.endsWith("\n") ? envContent : `${envContent}\n`;
  return `${normalized}${line}\n`;
}

/** Upsert VITE_API_BASE_URL into an existing frontend .env. */
export function upsertFrontendApiBaseUrlEnv(
  envContent: string,
  port: number = resolveBackendPort(),
): string {
  const url = buildFrontendApiBaseUrl(port);
  const line = `VITE_API_BASE_URL=${url}`;
  if (!envContent.trim()) return `${line}\n`;
  if (/^\s*VITE_API_BASE_URL\s*=.*$/m.test(envContent)) {
    return envContent.replace(/^\s*VITE_API_BASE_URL\s*=.*$/m, line);
  }
  const normalized = envContent.endsWith("\n") ? envContent : `${envContent}\n`;
  return `${normalized}${line}\n`;
}

/** Same Privy dashboard app ID as frontend `VITE_PRIVY_*` — required server-side for `verifyAccessToken`. */
export function upsertBackendPrivyAppIdMirror(
  envContent: string,
  privyAppId: string | null | undefined,
): string {
  const v = (privyAppId ?? "").trim();
  if (!v) return envContent;
  const line = `PRIVY_APP_ID=${JSON.stringify(v)}`;
  if (!envContent.trim()) return `${line}\n`;
  if (/^\s*PRIVY_APP_ID\s*=/m.test(envContent)) {
    return envContent.replace(/^\s*PRIVY_APP_ID\s*=.*$/m, line);
  }
  const normalized = envContent.endsWith("\n") ? envContent : `${envContent}\n`;
  return `${normalized}${line}\n`;
}

/** Read `VITE_PRIVY_APP_ID` / `NEXT_PUBLIC_PRIVY_APP_ID` from filled resource-requirements payloads. */
export function resolvePrivyAppIdMirrorFromFilledResources(
  filledResources: Array<{ envKey: string; value?: string | null }>,
): string | null {
  for (const key of ["VITE_PRIVY_APP_ID", "NEXT_PUBLIC_PRIVY_APP_ID"] as const) {
    const r = filledResources.find((x) => x.envKey === key);
    const v = (r?.value ?? "").trim();
    if (v.length > 0) return v;
  }
  return null;
}

/**
 * Upsert JWT_SECRET and JWT_EXPIRES_IN into an existing .env payload.
 * Only adds them if they are not already present, so user-set values are preserved.
 */
export function upsertJwtEnvVars(envContent: string): string {
  let result = envContent.endsWith("\n") ? envContent : `${envContent}\n`;

  if (!/^\s*JWT_SECRET\s*=/m.test(result)) {
    result += `JWT_SECRET=${JSON.stringify(generateJwtSecret())}\n`;
  }
  if (!/^\s*JWT_EXPIRES_IN\s*=/m.test(result)) {
    result += `JWT_EXPIRES_IN="7d"\n`;
  }
  return result;
}
