export type { RalphConfig } from "@/lib/ralph";
export { DEFAULT_RALPH_CONFIG } from "@/lib/ralph";

export type PipelineStepId =
  | "intent"
  | "prd"
  | "trd"
  | "sysdesign"
  | "implguide"
  | "design"
  | "pencil"
  | "mockup"
  | "qa"
  | "verify"
  | "kickoff";

export type PipelineStatus = "idle" | "running" | "completed" | "failed";

export interface StepResult {
  stepId: PipelineStepId;
  status: PipelineStatus;
  content?: string;
  model?: string;
  costUsd?: number;
  durationMs?: number;
  tokenUsage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
  traceId?: string;
  error?: string;
  timestamp: string;
  /** Extra structured data attached to a step (e.g. mockup file paths). */
  metadata?: Record<string, unknown>;
}

export interface PipelineRun {
  id: string;
  sessionId: string;
  featureBrief: string;
  status: PipelineStatus;
  currentStep: PipelineStepId | null;
  steps: Record<PipelineStepId, StepResult | null>;
  totalCostUsd: number;
  createdAt: string;
  updatedAt: string;
}

export interface PipelineEvent {
  type:
    | "step_start"
    | "step_complete"
    | "step_error"
    | "pipeline_complete"
    | "step_stream";
  runId: string;
  stepId: PipelineStepId;
  data: Partial<StepResult> & {
    /** Streaming chunk text (only for step_stream events) */
    chunk?: string;
    /** Whether the chunk is a thinking/reasoning token or main content */
    chunkType?: "thinking" | "content";
  };
}

export type KickoffTaskExecutionKind = "ai_autonomous" | "human_confirm_after";

export interface TaskSubStep {
  step: number;
  action: string;
  detail: string;
}

export interface TaskTokenEstimate {
  inputTokens: number;
  outputTokens: number;
  totalTokens: number;
  estimatedCostUsd: number;
}

export interface TaskFilePlan {
  creates: string[];
  modifies: string[];
  reads: string[];
}

export interface KickoffWorkItem {
  id: string;
  phase: string;
  title: string;
  description: string;
  estimatedHours: number;
  executionKind: KickoffTaskExecutionKind;
  files?: string[] | TaskFilePlan;
  dependencies?: string[];
  priority?: "P0" | "P1" | "P2";
  subSteps?: TaskSubStep[];
  tokenEstimate?: TaskTokenEstimate;
  acceptanceCriteria?: string[];
  /** PRD requirement IDs this task implements (AC-*, FR-*), for coverage gates. */
  coversRequirementIds?: string[];
}

// ─── Multi-Agent Coding Session ───

export type CodingAgentRole = "architect" | "frontend" | "backend" | "test";

export type CodingTaskStatus =
  | "pending"
  | "queued"
  | "in_progress"
  | "completed"
  | "completed_with_warnings"
  | "failed";

export interface CodingTask extends KickoffWorkItem {
  assignedAgentId: string | null;
  codingStatus: CodingTaskStatus;
  output?: string;
  generatedFiles?: string[];
  error?: string;
  startedAt?: string;
  completedAt?: string;
  /** Phase 1: verify/fix loop tracking */
  fixAttempts?: number;
  verifyErrors?: string;
  /** Real-time UI stage for the current task lifecycle. */
  progressStage?: "generating" | "verifying" | "fixing";
  /** Short preview of the latest verification error. */
  errorPreview?: string;
  /** Actual per-task generation token usage from coding stage. */
  tokenUsage?: {
    promptTokens: number;
    completionTokens: number;
    totalTokens: number;
  };
  /** Actual per-task generation cost from coding stage. */
  taskCostUsd?: number;
  /** Explicit list of modified files for this task (same as generatedFiles). */
  modifiedFiles?: string[];
}

export interface CodingAgentInstance {
  id: string;
  role: CodingAgentRole;
  label: string;
  status: "idle" | "working" | "completed" | "failed";
  currentTaskId: string | null;
  completedTaskIds: string[];
  failedTaskIds: string[];
  logs: AgentLogEntry[];
  totalCostUsd: number;
}

export type AgentLogType =
  | "info"
  | "task_start"
  | "task_progress"
  | "task_complete"
  | "task_error"
  | "task_verify"
  | "task_fix";

export interface AgentLogEntry {
  timestamp: string;
  type: AgentLogType;
  taskId?: string;
  message: string;
  details?: string;
}

export interface CodingSession {
  id: string;
  runId: string;
  status: "pending" | "running" | "completed" | "failed";
  agents: CodingAgentInstance[];
  tasks: CodingTask[];
  outputDir: string;
  totalCostUsd: number;
  createdAt: string;
  updatedAt: string;
  /** All files generated by agents so far; injected into downstream agent context on phase switch. */
  fileRegistry: FileRegistryEntry[];
}

export interface FileRegistryEntry {
  /** Relative path from outputDir, e.g. "src/services/orders.service.ts" */
  path: string;
  /** Role of the agent that generated this file */
  role: CodingAgentRole;
  /** One-line summary of the file's purpose, written when the task completes */
  summary: string;
  /** Primary exported identifiers (function/class/type names) for downstream reference */
  exports: string[];
}

export interface AgentWorkingMemory {
  /** Summaries of tasks this agent has completed so far in the session */
  completedTaskSummaries: Array<{
    taskId: string;
    taskTitle: string;
    filesGenerated: string[];
    summary: string;
  }>;
}

export interface CodingSessionEvent {
  type:
    | "session_start"
    | "agent_created"
    | "tasks_assigned"
    | "agent_task_start"
    | "agent_task_progress"
    | "agent_task_complete"
    | "agent_task_error"
    | "agent_idle"
    | "agent_completed"
    | "agent_log"
    | "integration_verify_start"
    | "integration_verify_result"
    | "integration_fix_result"
    | "task_refinement_start"
    | "task_refinement_complete"
    | "agent_task_substeps"
    | "gap_analysis_start"
    | "gap_analysis_complete"
    | "supplementary_dispatch"
    | "session_complete"
    | "session_error";
  sessionId: string;
  agentId?: string;
  taskId?: string;
  data: Record<string, unknown>;
}

export interface SupplementaryTask extends CodingTask {
  isSupplementary: true;
  gapDescription: string;
}
