package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"errors"
	"fmt"

	"github.com/aerocommerce/catalog-pim/graph/model"
	dbmodels "github.com/aerocommerce/catalog-pim/models"
	"gorm.io/gorm"
)

// Variants is the resolver for the variants field on Product.
func (r *productResolver) Variants(ctx context.Context, obj *model.Product) ([]*model.Variant, error) {
	var dbVariants []dbmodels.Variant

	// Fetch variants for the given product ID using GORM
	err := r.DB.WithContext(ctx).
		Where("product_id = ?", obj.ID).
		Find(&dbVariants).Error

	if err != nil {
		return nil, fmt.Errorf("failed to fetch variants: %w", err)
	}

	// Map DB models to GraphQL models
	gqlVariants := make([]*model.Variant, len(dbVariants))
	for i, v := range dbVariants {
		gqlVariants[i] = mapDBVariantToGQL(&v)
	}

	return gqlVariants, nil
}

// Product is the resolver for the product query.
func (r *queryResolver) Product(ctx context.Context, id string) (*model.Product, error) {
	var dbProduct dbmodels.Product

	// Fetch a single product by ID
	err := r.DB.WithContext(ctx).
		Where("id = ?", id).
		First(&dbProduct).Error

	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return nil, fmt.Errorf("product with id %s not found", id)
		}
		return nil, fmt.Errorf("failed to fetch product: %w", err)
	}

	return mapDBProductToGQL(&dbProduct), nil
}

// Products is the resolver for the products query.
func (r *queryResolver) Products(ctx context.Context, limit *int, offset *int) ([]*model.Product, error) {
	var dbProducts []dbmodels.Product

	// Build the query
	query := r.DB.WithContext(ctx).Model(&dbmodels.Product{})

	// Apply pagination if provided
	if limit != nil {
		query = query.Limit(*limit)
	} else {
		query = query.Limit(50) // Default limit
	}

	if offset != nil {
		query = query.Offset(*offset)
	}

	// Execute query
	if err := query.Find(&dbProducts).Error; err != nil {
		return nil, fmt.Errorf("failed to fetch products: %w", err)
	}

	// Map DB models to GraphQL models
	gqlProducts := make([]*model.Product, len(dbProducts))
	for i, p := range dbProducts {
		gqlProducts[i] = mapDBProductToGQL(&p)
	}

	return gqlProducts, nil
}

// Product returns ProductResolver implementation.
func (r *Resolver) Product() ProductResolver { return &productResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type productResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }

// --- Helper Mapping Functions ---

func mapDBProductToGQL(p *dbmodels.Product) *model.Product {
	if p == nil {
		return nil
	}
	
	// Convert description to pointer if it's a string in DB but optional in GQL
	var desc *string
	if p.Description != "" {
		desc = &p.Description
	}

	return &model.Product{
		ID:          p.ID.String(),
		Name:        p.Name,
		Description: desc,
		VendorID:    p.VendorID.String(),
		CreatedAt:   p.CreatedAt.Format("2006-01-02T15:04:05Z"),
		UpdatedAt:   p.UpdatedAt.Format("2006-01-02T15:04:05Z"),
	}
}

func mapDBVariantToGQL(v *dbmodels.Variant) *model.Variant {
	if v == nil {
		return nil
	}
	return &model.Variant{
		ID:                v.ID.String(),
		ProductID:         v.ProductID.String(),
		Sku:               v.SKU,
		Price:             v.Price,
		InventoryQuantity: v.InventoryQuantity,
	}
}
