package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen

import (
	"context"
	"fmt"
	"time"

	"github.com/aerocommerce/cart-checkout/cart"
	"github.com/aerocommerce/cart-checkout/graph/model"
)

type mutationResolver struct{ *Resolver }

// AddToCart is the resolver for the addToCart mutation.
func (r *mutationResolver) AddToCart(ctx context.Context, input model.AddToCartInput) (*model.Cart, error) {
	var cartID string
	if input.CartID != nil {
		cartID = *input.CartID
	}

	// Map GraphQL input to internal domain model
	item := cart.CartItem{
		ProductID: input.ProductID,
		VariantID: input.VariantID,
		Quantity:  input.Quantity,
	}

	// Delegate to Cart Manager for Redis state management
	updatedCart, err := r.CartManager.AddToCart(ctx, cartID, item)
	if err != nil {
		return nil, fmt.Errorf("failed to add item to cart: %w", err)
	}

	// Map internal domain model back to GraphQL response model
	gqlItems := make([]*model.CartItem, len(updatedCart.Items))
	for i, it := range updatedCart.Items {
		gqlItems[i] = &model.CartItem{
			ProductID: it.ProductID,
			VariantID: it.VariantID,
			Quantity:  it.Quantity,
		}
	}

	return &model.Cart{
		ID:        updatedCart.ID,
		Items:     gqlItems,
		UpdatedAt: updatedCart.UpdatedAt.Format(time.RFC3339),
	}, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }
