/**
 * Summarize design-step user revisions into a forward-looking guidance
 * pattern. Mirrors prd-diff-summarize.ts but tuned for HTML design specs.
 */

import {
  chatCompletion,
  resolveModel,
  type ChatMessage,
} from "@/lib/openrouter";
import { MODEL_CONFIG } from "@/lib/model-config";
import type { ProjectTier } from "@/lib/agents/shared/project-classifier";

const SUMMARIZE_PROMPT = `You are extracting a Design-improvement pattern from a diff.

INPUTS:
- Project tier (S / M / L) and type (e.g. "calculator", "dashboard").
- Original design spec (HTML) generated by an AI agent.
- Final design spec (HTML) after the user reviewed and edited it.

YOUR JOB:
Identify the SINGLE most important design choice that was changed (or that was missing in the original). Speak in concrete design terms — colour palette, typography, spacing, component shape, density, dark vs light, accessibility — not vague aesthetics.

OUTPUT FORMAT — exactly two sections, in plain markdown, no preamble:

### Title
A one-line summary (≤ 80 chars) suitable as a memory record title.

### Pattern
A 2-4 sentence guidance string. Cite specific tokens / colours / sizes when relevant (e.g. "use #1a1a2e background with #e94560 accent" rather than "use a darker palette"). Make it actionable. Do NOT mention the words "diff", "user", or "original" — write it as forward-looking guidance for the next design generation.`;

export interface DesignDiffSummaryInput {
  tier: ProjectTier;
  projectType: string;
  originalDesign: string;
  finalDesign: string;
}

export interface DesignDiffSummary {
  title: string;
  pattern: string;
  modelUsed: string;
}

const MAX_HTML_CHARS = 8000;

function truncate(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n) + "\n... (truncated)";
}

function stripDiffSummaryFences(raw: string): {
  title: string;
  pattern: string;
} | null {
  const titleMatch = raw.match(/###\s*Title\s*\n+([\s\S]*?)(?:\n###|$)/i);
  const patternMatch = raw.match(/###\s*Pattern\s*\n+([\s\S]*)$/i);
  if (!titleMatch || !patternMatch) return null;
  const title = titleMatch[1].trim().split("\n")[0].slice(0, 120);
  const pattern = patternMatch[1].trim();
  if (!title || !pattern) return null;
  return { title, pattern };
}

export async function summarizeDesignDiff(
  input: DesignDiffSummaryInput,
): Promise<DesignDiffSummary | null> {
  const userMsg = [
    `Project tier: ${input.tier}`,
    `Project type: ${input.projectType}`,
    "",
    "## Original design (AI draft)",
    truncate(input.originalDesign, MAX_HTML_CHARS),
    "",
    "## Final design (after user edits)",
    truncate(input.finalDesign, MAX_HTML_CHARS),
  ].join("\n");

  const messages: ChatMessage[] = [
    { role: "system", content: SUMMARIZE_PROMPT },
    { role: "user", content: userMsg },
  ];

  try {
    const model = resolveModel(MODEL_CONFIG.qa);
    const response = await chatCompletion(messages, {
      model,
      temperature: 0.2,
      max_tokens: 400,
    });
    const content = response.choices?.[0]?.message?.content?.trim() ?? "";
    if (!content) return null;
    const parsed = stripDiffSummaryFences(content);
    if (!parsed) return null;
    return { ...parsed, modelUsed: model };
  } catch (err) {
    console.warn(
      "[memory] summarizeDesignDiff failed (skipping):",
      (err as Error).message,
    );
    return null;
  }
}
