/**
 * Summarize the difference between an LLM-generated PRD and the user's
 * final (post-edit) PRD into a short, prompt-friendly natural-language
 * pattern that the next PRD agent can consume verbatim.
 *
 * Uses a cheap model (gpt-5.4-mini class) because this runs on every
 * PRD confirmation and we don't want to add meaningful latency.
 *
 * Returns null when:
 *   - LLM call fails (caller should fall back to a generic "user edited" record)
 *   - Diff is too small to be worth summarising
 */

import {
  chatCompletion,
  resolveModel,
  type ChatMessage,
} from "@/lib/openrouter";
import { MODEL_CONFIG } from "@/lib/model-config";
import type { ProjectTier } from "@/lib/agents/shared/project-classifier";

const SUMMARIZE_PROMPT = `You are extracting a PRD-improvement pattern from a diff.

INPUTS:
- Project tier (S / M / L) and type (e.g. "calculator", "dashboard").
- Original PRD generated by an AI agent.
- Final PRD after the user reviewed and edited it.

YOUR JOB:
Identify the SINGLE most important way the original PRD fell short, in language the next PRD agent can use as guidance. Examples:
  - "S-tier calculator PRDs frequently omit explicit keyboard shortcut mappings (Backspace / Enter / Escape). Always list every key → action pair in the Keyboard Support feature."
  - "M-tier dashboard PRDs often understate empty-state copy. Specify the empty state's heading, body text, and CTA in every list/table page."

OUTPUT FORMAT — exactly two sections, in plain markdown, no preamble:

### Title
A one-line summary (≤ 80 chars) suitable as a memory record title.

### Pattern
A 2-4 sentence guidance string. Refer to specific PRD sections by name when relevant. Make it actionable and concrete. Do NOT mention the words "diff", "user", or "original" — write it as forward-looking guidance.`;

export interface PrdDiffSummaryInput {
  tier: ProjectTier;
  projectType: string;
  originalPrd: string;
  finalPrd: string;
}

export interface PrdDiffSummary {
  title: string;
  pattern: string;
  modelUsed: string;
}

const MAX_PRD_CHARS = 6000; // cap each side for the cheap model

function truncate(s: string, n: number): string {
  if (s.length <= n) return s;
  return s.slice(0, n) + "\n... (truncated)";
}

function stripDiffSummaryFences(raw: string): {
  title: string;
  pattern: string;
} | null {
  const titleMatch = raw.match(/###\s*Title\s*\n+([\s\S]*?)(?:\n###|$)/i);
  const patternMatch = raw.match(/###\s*Pattern\s*\n+([\s\S]*)$/i);
  if (!titleMatch || !patternMatch) return null;
  const title = titleMatch[1].trim().split("\n")[0].slice(0, 120);
  const pattern = patternMatch[1].trim();
  if (!title || !pattern) return null;
  return { title, pattern };
}

export async function summarizePrdDiff(
  input: PrdDiffSummaryInput,
): Promise<PrdDiffSummary | null> {
  const userMsg = [
    `Project tier: ${input.tier}`,
    `Project type: ${input.projectType}`,
    "",
    "## Original PRD (AI draft)",
    truncate(input.originalPrd, MAX_PRD_CHARS),
    "",
    "## Final PRD (after user edits)",
    truncate(input.finalPrd, MAX_PRD_CHARS),
  ].join("\n");

  const messages: ChatMessage[] = [
    { role: "system", content: SUMMARIZE_PROMPT },
    { role: "user", content: userMsg },
  ];

  try {
    const model = resolveModel(MODEL_CONFIG.qa); // cheap class — gpt-4o-mini today
    const response = await chatCompletion(messages, {
      model,
      temperature: 0.2,
      max_tokens: 400,
    });
    const content = response.choices?.[0]?.message?.content?.trim() ?? "";
    if (!content) return null;
    const parsed = stripDiffSummaryFences(content);
    if (!parsed) return null;
    return { ...parsed, modelUsed: model };
  } catch (err) {
    console.warn(
      "[memory] summarizePrdDiff failed (skipping):",
      (err as Error).message,
    );
    return null;
  }
}
